<#
.SYNOPSIS
    Purple Team Phase 2 defensive hunter - Discovery, Collection, and Exfiltration activity.

.DESCRIPTION
    Hunts for indicators generated by the Phase 2 offensive demos using Sysmon telemetry.

    Focus areas:
    - Discovery   : Sysmon Event ID 1 (Process Create) for common enumeration binaries
                    launched from powershell.exe (systeminfo, tasklist, whoami, ipconfig, etc.)
    - Collection  : Sysmon Event ID 11 (FileCreate) for staging paths, archives, and
                    bulk file copies under known lab staging folders
    - Exfiltration: Sysmon Event ID 11 for EXFIL_ named files / drop-folder activity
                    (may be limited by Sysmon configuration)

    Designed for the SANS SEC504 Windows 10 lab with Sysmon installed.
    Requires Administrator rights to read the Sysmon Operational log.

.NOTES
    Author          : B. Underhill infosec-portfolio / Purple Team ATT&CK series
                        Developed with assistence of xAI Grok
    Lab             : SANS SEC504 Windows 10 Enterprise
    MITRE ATT&CK    : T1082, T1057, T1087, T1016, T1083, T1005, T1119, T1560.001, T1041, T1020
    Requires        : Administrator + Sysmon
    Ethical Use     : AUTHORIZED LAB / DEFENSIVE USE ONLY

.EXAMPLE
    .\Detect-DiscoveryCollectionExfil.ps1

.EXAMPLE
    .\Detect-DiscoveryCollectionExfil.ps1 -TimeWindowMinutes 120 -OutputPath .\Phase2-Hunt.csv
#>

param(
    [int]$TimeWindowMinutes = 90,
    [string]$OutputPath = ".\Phase2-HuntReport_$(Get-Date -Format 'yyyyMMdd_HHmm').csv"
)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
function Write-HuntLog {
    param([string]$Message, [string]$Level = "INFO")
    $ts = Get-Date -Format "yyyy-MM-dd HH:mm:ss"
    $line = "[$ts] [$Level] $Message"
    switch ($Level) {
        "ALERT"   { Write-Host $line -ForegroundColor Red }
        "WARNING" { Write-Host $line -ForegroundColor Yellow }
        "FOUND"   { Write-Host $line -ForegroundColor Green }
        default   { Write-Host $line }
    }
}

function Get-SysmonEvents {
    param(
        [int]$EventId,
        [datetime]$StartTime,
        [int]$MaxEvents = 500
    )
    try {
        $events = Get-WinEvent -FilterHashtable @{
            LogName   = 'Microsoft-Windows-Sysmon/Operational'
            Id        = $EventId
            StartTime = $StartTime
        } -MaxEvents $MaxEvents -ErrorAction Stop
        return $events
    }
    catch {
        return @()
    }
}

# ---------------------------------------------------------------------------
# Banner
# ---------------------------------------------------------------------------
Write-Host ""
Write-Host "========================================================================" -ForegroundColor Cyan
Write-Host "  PURPLE TEAM PHASE 2 - DEFENSIVE HUNT" -ForegroundColor Cyan
Write-Host "  Discovery / Collection / Exfiltration" -ForegroundColor Cyan
Write-Host "========================================================================" -ForegroundColor Cyan
Write-Host ""

$startTime = (Get-Date).AddMinutes(-$TimeWindowMinutes)
Write-HuntLog "Time window : last $TimeWindowMinutes minutes (since $($startTime.ToString('yyyy-MM-dd HH:mm:ss')))"
Write-HuntLog "Output CSV  : $OutputPath"
Write-Host ""

$findings = @()

# ===========================================================================
# 1. DISCOVERY - Sysmon Event ID 1 (Process Create)
# ===========================================================================
Write-HuntLog "=== DISCOVERY (Sysmon EID 1) ===" -Level "INFO"

$discoveryBinaries = @(
    'systeminfo\.exe',
    'tasklist\.exe',
    'whoami\.exe',
    'ipconfig\.exe',
    'hostname\.exe',
    'net\.exe',
    'netstat\.exe',
    'quser\.exe',
    'query\.exe'
)

$eid1 = Get-SysmonEvents -EventId 1 -StartTime $startTime -MaxEvents 400

if ($eid1.Count -eq 0) {
    Write-HuntLog "No Sysmon Event ID 1 events found in the time window." -Level "WARNING"
}
else {
    Write-HuntLog "Retrieved $($eid1.Count) Process Create events. Scanning for discovery tools..."

    foreach ($evt in $eid1) {
        $msg = $evt.Message
        if (-not $msg) { continue }

        foreach ($bin in $discoveryBinaries) {
            if ($msg -match $bin) {
                # Extract key fields with simple regex
                $image       = if ($msg -match 'Image:\s*(.+)') { $matches[1].Trim() } else { 'n/a' }
                $parentImage = if ($msg -match 'ParentImage:\s*(.+)') { $matches[1].Trim() } else { 'n/a' }
                $commandLine = if ($msg -match 'CommandLine:\s*(.+)') { $matches[1].Trim() } else { 'n/a' }
                $user        = if ($msg -match 'User:\s*(.+)') { $matches[1].Trim() } else { 'n/a' }

                $technique = switch -Regex ($bin) {
                    'systeminfo' { 'T1082 System Information Discovery' }
                    'tasklist'   { 'T1057 Process Discovery' }
                    'whoami'     { 'T1087 Account Discovery' }
                    'ipconfig'   { 'T1016 Network Configuration Discovery' }
                    'hostname'   { 'T1082 System Information Discovery' }
                    'net\.exe'   { 'T1087 / T1135 Account or Network Share Discovery' }
                    'netstat'    { 'T1049 System Network Connections Discovery' }
                    default      { 'Discovery activity' }
                }

                $findings += [PSCustomObject]@{
                    Timestamp  = $evt.TimeCreated
                    Tactic     = 'Discovery'
                    Technique  = $technique
                    EventId    = 1
                    Image      = $image
                    ParentImage= $parentImage
                    CommandLine= $commandLine
                    User       = $user
                    TargetFile = ''
                    Notes      = 'Native discovery binary'
                }

                Write-HuntLog ("FOUND  {0}  |  {1}  |  Parent: {2}" -f $evt.TimeCreated.ToString('HH:mm:ss'), $technique, $parentImage) -Level "FOUND"
                break
            }
        }
    }
}

Write-Host ""

# ===========================================================================
# 2. COLLECTION / EXFILTRATION - Sysmon Event ID 11 (FileCreate)
# ===========================================================================
Write-HuntLog "=== COLLECTION / EXFILTRATION (Sysmon EID 11) ===" -Level "INFO"

# Patterns that indicate staging or simulated exfil in this lab
$stagingPatterns = @(
    'PurpleTeam-Phase2',
    'CollectedData_',
    'EXFIL_',
    '\\Collection\\',
    '\\Exfiltration\\',
    '\\Archive\\',
    '\\Drop\\',
    'Staging',
    'Transfer-Log'
)

$eid11 = Get-SysmonEvents -EventId 11 -StartTime $startTime -MaxEvents 500

if ($eid11.Count -eq 0) {
    Write-HuntLog "No Sysmon Event ID 11 events found in the time window." -Level "WARNING"
    Write-HuntLog "Note: Lab Sysmon config may filter many FileCreate events." -Level "WARNING"
}
else {
    Write-HuntLog "Retrieved $($eid11.Count) FileCreate events. Scanning for staging / exfil patterns..."

    $matched = 0
    foreach ($evt in $eid11) {
        $msg = $evt.Message
        if (-not $msg) { continue }

        $isMatch = $false
        foreach ($pat in $stagingPatterns) {
            if ($msg -match $pat) {
                $isMatch = $true
                break
            }
        }
        if (-not $isMatch) { continue }

        $matched++
        $targetFile = if ($msg -match 'TargetFilename:\s*(.+)') { $matches[1].Trim() } else { 'n/a' }
        $image      = if ($msg -match 'Image:\s*(.+)') { $matches[1].Trim() } else { 'n/a' }
        $user       = if ($msg -match 'User:\s*(.+)') { $matches[1].Trim() } else { 'n/a' }

        # Classify tactic from path
        $tactic = 'Collection'
        $technique = 'T1005 / T1119 Data Staging'
        if ($targetFile -match 'EXFIL_|\\Exfiltration\\|\\Drop\\') {
            $tactic = 'Exfiltration'
            $technique = 'T1041 / T1020 Simulated Exfiltration'
        }
        elseif ($targetFile -match '\.zip|CollectedData_') {
            $technique = 'T1560.001 Archive Collected Data'
        }

        $findings += [PSCustomObject]@{
            Timestamp  = $evt.TimeCreated
            Tactic     = $tactic
            Technique  = $technique
            EventId    = 11
            Image      = $image
            ParentImage= ''
            CommandLine= ''
            User       = $user
            TargetFile = $targetFile
            Notes      = 'FileCreate in staging / exfil path'
        }

        Write-HuntLog ("FOUND  {0}  |  {1}  |  {2}" -f $evt.TimeCreated.ToString('HH:mm:ss'), $technique, $targetFile) -Level "FOUND"
    }

    if ($matched -eq 0) {
        Write-HuntLog "No FileCreate events matched staging/exfil patterns." -Level "WARNING"
        Write-HuntLog "This is expected on some lab Sysmon configs that filter .zip/.txt creates." -Level "WARNING"
    }
}

Write-Host ""

# ===========================================================================
# 3. Summary + export
# ===========================================================================
Write-HuntLog "=== SUMMARY ===" -Level "INFO"

if ($findings.Count -eq 0) {
    Write-HuntLog "No Phase 2 related activity detected in the time window." -Level "WARNING"
    Write-HuntLog "Tips: Re-run the offensive demos, then re-run this hunter with a wider -TimeWindowMinutes." -Level "INFO"
}
else {
    $byTactic = $findings | Group-Object Tactic
    foreach ($g in $byTactic) {
        Write-HuntLog ("{0,-14} : {1} finding(s)" -f $g.Name, $g.Count) -Level "FOUND"
    }

    Write-Host ""
    Write-Host "Detailed findings:" -ForegroundColor Cyan
    $findings |
        Sort-Object Timestamp |
        Format-Table Timestamp, Tactic, Technique, EventId, Image, TargetFile -AutoSize -Wrap

    # Export CSV
    try {
        $findings | Sort-Object Timestamp | Export-Csv -Path $OutputPath -NoTypeInformation -Encoding UTF8
        Write-HuntLog "Results exported to: $OutputPath" -Level "INFO"
    }
    catch {
        Write-HuntLog "Failed to write CSV: $($_.Exception.Message)" -Level "WARNING"
    }
}

Write-Host ""
Write-HuntLog "Hunt complete." -Level "INFO"
Write-Host ""
Write-Host "Known limitation: Sysmon FileCreate (EID 11) coverage depends on the active" -ForegroundColor Yellow
Write-Host "Sysmon configuration. Some lab images filter .zip / .txt creation events." -ForegroundColor Yellow
Write-Host "Discovery (EID 1) detections remain the highest-confidence signal." -ForegroundColor Yellow
Write-Host ""
